#!/usr/bin/env bash
#https://github.com/bids-standard/bids-validator
# use BIDS validator using the latest docker image

# if no arguments are given
if [[ $# = 0 ]]; then
	echo "Usage: is_bids_dock [directory]"
	exit 1
fi

# check for verbosity
verb=''
while (( $# > 1 )); do
	case "$1" in
		"-v")
		shift
		verb='--verbose'
		;;
	esac
done

# grab last argument and create full path
for i in $@; do :; done
dir=`pwd`
dataset="${i}"

# check if directory exists and run validator
if [[ -d "${dir}/${dataset}" ]]; then
	docker run -ti --rm -v "${dir}/${dataset}:/data:ro" bids/validator:latest ${verb} /data
else
	echo "${dir}/${dataset} does not exist..."
	exit 1
fi