#!/usr/bin/env bash
#https://github.com/bids-standard/bids-validator
# use BIDS validator using a singularity image
# must have acces to /data/DSST

# if no arguments are given
if [[ $# = 0 ]]; then
	echo "Usage: is_bids_sing [directory]"
	exit 1
fi

# check for verbosity
verb=''
while (( $# > 1 )); do
	case "$1" in
		"-v")
		shift
		verb='--verbose'
		;;
	esac
done

# check if singularity image exists
image=/data/DSST/containers/bids-validator-1.2.5.simg
if [[ ! -f "${image}" ]]; then
	echo "Singularity image not found"
	exit 1
fi

# grab last argument and create full path
for i in $@; do :; done
dir=`pwd`
dataset="${i}"

# check if directory exists and run validator
if [[ -d "${dir}/${dataset}" ]]; then
	module load singularity
	singularity run -B ${1}:/data /data/DSST/containers/bids-validator-1.2.5.simg ${verb} /data
else
	echo "${dir}/${dataset} does not exist..."
	exit 1
fi